### ISSUE TITLE
No chart output in Jupyter Notebook with custom kernel

### ISSUE THREAD

**Issue by victorlin** [vega/ipyvega#152]
I've installed jupyter on the base anaconda environment and vega on a custom anaconda environment whose kernel I've added to the base jupyter. While attempting to replicate the example notebooks using the custom kernel, I am unable to see any visual output from the chart objects. There does not seem to be any JS console errors/messages.

![image](https://user-images.githubusercontent.com/13424970/71598813-40c58380-2afd-11ea-953f-4faa535c1447.png)

This issue was mitigated by installing vega on the base anaconda environment, though the documentation does not explicitly say to do so.

**Comment by jakevdp** [comment]
Since this package is a frontend extension, it must be installed in the runtime from which jupyter is launched. It sounds like you launched your jupyter runtime from the base anaconda environment, which is why the package must be installed there.

If there's a way you think this could be made more clear in the README, feel free to open a pull request.
