### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by domoritz** [vega/ipyvega#21]
- [ ] Is the spec is not valid, show an error

**Comment by ellisonbg** [comment]
Would this be on the python side or JS side?

**Comment by domoritz** [comment]
The specific example above would have to be on the js side.

**Comment by falconair** [comment]
This is a huge problem! If there is an error, I have to open the developer console in chrome and all that tells me is "Cannot read property 'view' of undefined or other cryptic message from deep within the library. I have to debug javascript + python via the browser. 

Since vega is supposed to be declarative json, there should be a way to verify it before going deeper into the library!

**Comment by domoritz** [comment]
I agree with @falconair. We should be using https://github.com/vega/schema to validate the spec. However, note that I haven't found a schema validator with good error message yet and there may still be a disconnect between python and javascript code.

**Comment by kanitw** [comment]
There are also warning that Vega-lite compiler (and Vega runtime) generates  -- maybe passing a logger that communicates with python would be helpful?  (Of course you know this codebase better.)

**Comment by domoritz** [comment]
Note that this plugin is only here until it will be deprecated. See https://github.com/vega/ipyvega/issues/67#issuecomment-326057752.

**Comment by domoritz** [comment]
To address this issue we should first surface errors in the notebook. Then, we should use the Vega and Vega-Lite schemas to validate a spec (we could add this to Vega-Embed).
