### ISSUE TITLE
Will JupyterLab be supported?

### ISSUE THREAD

**Issue by jpivarski** [vega/ipyvega#90]
Out of the box, ipyvega can't draw plots in JupyterLab because of this tightened security measure:

```
JavaScript output is disabled in JupyterLab
```

Some libraries, like Altair, have [managed to find a way around it](https://github.com/altair-viz/altair/issues/659). Are there any plans to do the same for ipyvega?

**Comment by jakevdp** [comment]
Nope. If you want to display vega-lite visualizations in JupyterLab, the recommended approach is to use Altair's renderer framework. ``ipyvega`` should be considered a compatibility layer for the classic notebook only :smile:

**Comment by jakevdp** [comment]
More details: Jupyterlab has vega and vega-lite built-in, and will automatically display any object that has a ``_repr_mimebundle_`` method with the appropriate mimetype. You can check out the Altair source if you want to see an example of how this can be used in your own objects.

**Comment by jpivarski** [comment]
Is ipyvega obsolete? Are Altair, ipyvega, and maybe Vincent developed by more or less the same group of people and each is a successor to the last?

**Comment by jakevdp** [comment]
> Is ipyvega obsolete?

No, it's the main supported way to display vega & vega-lite in the classic notebook, and is used by altair for that purpose.

> Are Altair, ipyvega, and maybe Vincent developed by more or less the same group of people 

Vincent was developed by a different group, and I'm not certain about it's status. Altair and ipyvega are more or less developed by a common group of people.

> and each is a successor to the last?

No. The purpose of ipyvega is to display vega & vega-lite plots in the classic notebook. The purpose of Altair is to provide a Python API to generate vega & vega-lite charts, and due to constraints in how charts are displayed among various frontends, it was cleaner to put the general display architecture for vega & vega-lite within Altair, while still depending on ipyvega for display in the legacy notebook.

That's why I recommended you depend on Altair if you want a general display solution for vega & vega-lite plots.

Hope that's clear.
